# Generated by Django 4.2.22 on 2026-04-02 16:03

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_destino(apps, schema_editor):
    TransferenciaEstoque = apps.get_model('estoque', 'TransferenciaEstoque')
    for transferencia in TransferenciaEstoque.objects.filter(
            empresa_destino__isnull=True, empresa__isnull=False):
        transferencia.empresa_destino_id = transferencia.empresa_id
        transferencia.save(update_fields=['empresa_destino'])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produtoempresa'),
        ('estoque', '0005_alter_localestoque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaestoque',
            name='empresa_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_estoque_recebidas', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='impacto_custo',
            field=models.CharField(choices=[('MAN', 'Manter custo atual do produto')], default='MAN', max_length=3),
        ),
        migrations.RunPython(
            backfill_empresa_destino, migrations.RunPython.noop),
    ]
