# Generated by Codex for Django 4 compatibility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170820_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentocaixa',
            options={
                'verbose_name': 'Movimento de Caixa',
                'permissions': (
                    ('acesso_fluxodecaixa', 'Pode acessar o Fluxo de Caixa'),
                ),
            },
        ),
    ]
