# Generated by Django 4.2.22 on 2026-04-02 13:58

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_financeiro(apps, schema_editor):
    Empresa = apps.get_model('cadastro', 'Empresa')
    Lancamento = apps.get_model('financeiro', 'Lancamento')
    MovimentoCaixa = apps.get_model('financeiro', 'MovimentoCaixa')

    empresa = Empresa.objects.order_by('pk').first()
    if empresa is None:
        return

    Lancamento.objects.filter(empresa__isnull=True).update(empresa=empresa)
    MovimentoCaixa.objects.filter(empresa__isnull=True).update(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_usuarioempresa'),
        ('financeiro', '0004_alter_movimentocaixa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'verbose_name': 'Lançamento'},
        ),
        migrations.AlterModelOptions(
            name='planocontasgrupo',
            options={'verbose_name': 'Grupo do Plano de Contas'},
        ),
        migrations.AddField(
            model_name='lancamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_caixa', to='cadastro.empresa'),
        ),
        migrations.RunPython(
            backfill_empresa_financeiro, migrations.RunPython.noop),
    ]
