# Generated by Django 4.2.22 on 2026-04-02 17:11

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_plano_contas(apps, schema_editor):
    Empresa = apps.get_model('cadastro', 'Empresa')
    PlanoContasGrupo = apps.get_model('financeiro', 'PlanoContasGrupo')
    empresa_padrao = Empresa.objects.order_by('pk').first()
    if empresa_padrao is None:
        return

    PlanoContasGrupo.objects.filter(empresa__isnull=True).update(
        empresa=empresa_padrao)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produtoempresa'),
        ('financeiro', '0005_alter_lancamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontasgrupo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_conta', to='cadastro.empresa'),
        ),
        migrations.RunPython(backfill_empresa_plano_contas, noop),
    ]
