# Generated by Django 4.2.22 on 2026-04-02 15:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def backfill_produto_empresa(apps, schema_editor):
    Produto = apps.get_model('cadastro', 'Produto')
    Empresa = apps.get_model('cadastro', 'Empresa')
    ProdutoEmpresa = apps.get_model('cadastro', 'ProdutoEmpresa')

    empresas = list(Empresa.objects.all())
    if not empresas:
        return

    configuracoes = []
    for produto in Produto.objects.all():
        for empresa in empresas:
            configuracoes.append(ProdutoEmpresa(
                produto=produto,
                empresa=empresa,
                custo=produto.custo,
                venda=produto.venda,
                cfop_padrao=produto.cfop_padrao,
                grupo_fiscal=produto.grupo_fiscal,
            ))
    ProdutoEmpresa.objects.bulk_create(configuracoes, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_alter_grupofiscal_options_and_more'),
        ('cadastro', '0007_alter_categoria_options_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cfop_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.naturezaoperacao')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_produto', to='cadastro.empresa')),
                ('grupo_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.grupofiscal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_empresa', to='cadastro.produto')),
            ],
            options={
                'verbose_name': 'Configuracao de Produto por Empresa',
                'unique_together': {('produto', 'empresa')},
            },
        ),
        migrations.RunPython(
            backfill_produto_empresa, migrations.RunPython.noop),
    ]
