# Generated by Django 4.2.22 on 2026-04-02 17:38

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_fiscal(apps, schema_editor):
    Empresa = apps.get_model('cadastro', 'Empresa')
    GrupoFiscal = apps.get_model('fiscal', 'GrupoFiscal')
    NaturezaOperacao = apps.get_model('fiscal', 'NaturezaOperacao')
    empresa_padrao = Empresa.objects.order_by('pk').first()
    if empresa_padrao is None:
        return

    GrupoFiscal.objects.filter(empresa__isnull=True).update(
        empresa=empresa_padrao)
    NaturezaOperacao.objects.filter(empresa__isnull=True).update(
        empresa=empresa_padrao)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produtoempresa'),
        ('fiscal', '0005_alter_grupofiscal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupofiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_fiscais', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='naturezaoperacao',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naturezas_operacao', to='cadastro.empresa'),
        ),
        migrations.RunPython(backfill_empresa_fiscal, noop),
    ]
