# Generated by Django 4.2.22 on 2026-04-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('cadastro', '0004_empresa_hierarquia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='cadastro.empresa')),
                ('m_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_permitidas', to='login.usuario')),
            ],
            options={
                'verbose_name': 'Empresa permitida do usuario',
                'unique_together': {('m_empresa', 'm_usuario')},
            },
        ),
    ]
