# Generated by Django 4.2.22 on 2026-04-02 14:36

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_relacionada(apps, schema_editor):
    Empresa = apps.get_model('cadastro', 'Empresa')
    Cliente = apps.get_model('cadastro', 'Cliente')
    Fornecedor = apps.get_model('cadastro', 'Fornecedor')
    Transportadora = apps.get_model('cadastro', 'Transportadora')

    empresa = Empresa.objects.order_by('pk').first()
    if empresa is None:
        return

    Cliente.objects.filter(empresa_relacionada__isnull=True).update(
        empresa_relacionada=empresa)
    Fornecedor.objects.filter(empresa_relacionada__isnull=True).update(
        empresa_relacionada=empresa)
    Transportadora.objects.filter(empresa_relacionada__isnull=True).update(
        empresa_relacionada=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_usuarioempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='empresa_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='empresa_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportadoras', to='cadastro.empresa'),
        ),
        migrations.RunPython(
            backfill_empresa_relacionada, migrations.RunPython.noop),
    ]
