# Generated by Codex for Django 4 compatibility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_auto_20170915_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaonotafiscal',
            options={
                'default_permissions': (),
                'verbose_name': 'Configuração NF-e',
                'permissions': (
                    ('configurar_nfe', 'Pode modificar configuração de NF-e'),
                ),
            },
        ),
    ]
