# Generated by Django 4.2.22 on 2026-04-02 13:58

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_configuracao(apps, schema_editor):
    Empresa = apps.get_model('cadastro', 'Empresa')
    ConfiguracaoNotaFiscal = apps.get_model('fiscal', 'ConfiguracaoNotaFiscal')

    empresa = Empresa.objects.order_by('pk').first()
    if empresa is None:
        return

    ConfiguracaoNotaFiscal.objects.filter(
        empresa__isnull=True).update(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_usuarioempresa'),
        ('fiscal', '0004_alter_configuracaonotafiscal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupofiscal',
            options={'verbose_name': 'Grupo Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='naturezaoperacao',
            options={'verbose_name': 'Natureza da Operação'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalentrada',
            options={'verbose_name': 'Nota Fiscal de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='notafiscalsaida',
            options={'permissions': (('emitir_notafiscal', 'Pode emitir notas fiscais'), ('cancelar_notafiscal', 'Pode cancelar notas fiscais'), ('gerar_danfe', 'Pode gerar DANFE/DANFCE'), ('consultar_cadastro', 'Pode consultar cadastro no SEFAZ'), ('inutilizar_notafiscal', 'Pode inutilizar notas fiscais'), ('consultar_notafiscal', 'Pode consultar notas fiscais'), ('baixar_notafiscal', 'Pode baixar notas fiscais'), ('manifestacao_destinatario', 'Pode efetuar manifestação do destinatário')), 'verbose_name': 'Nota Fiscal'},
        ),
        migrations.AddField(
            model_name='configuracaonotafiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_nfe', to='cadastro.empresa'),
        ),
        migrations.RunPython(
            backfill_empresa_configuracao, migrations.RunPython.noop),
    ]
