# Generated by Django 4.2.22 on 2026-04-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_localestoque_options_and_more'),
        ('compras', '0003_compra_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orcamentocompra',
            options={'verbose_name': 'Orçamento de Compra'},
        ),
        migrations.AlterModelOptions(
            name='pedidocompra',
            options={'permissions': (('faturar_pedidocompra', 'Pode faturar Pedidos de Compra'),), 'verbose_name': 'Pedido de Compra'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compra_local_estoque', to='estoque.localestoque'),
        ),
    ]
