# Generated by Django 4.2.22 on 2026-04-02 16:42

from django.db import migrations, models
import django.db.models.deletion


def backfill_empresa_destino(apps, schema_editor):
    Compra = apps.get_model('compras', 'Compra')
    for compra in Compra.objects.filter(empresa_destino__isnull=True, empresa__isnull=False):
        compra.empresa_destino_id = compra.empresa_id
        compra.save(update_fields=['empresa_destino'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produtoempresa'),
        ('compras', '0004_alter_orcamentocompra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='empresa_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras_destinadas', to='cadastro.empresa'),
        ),
        migrations.RunPython(backfill_empresa_destino, noop),
    ]
