# Generated by Django 4.2.22 on 2026-04-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20170714_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='empresa_pai',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name='filiais', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(
                choices=[('IND', 'Independente'), ('MAT', 'Matriz'), ('FIL', 'Filial')],
                default='IND', max_length=3),
        ),
    ]
